### ISSUE TITLE
Packaging Project - Build Fails

### ISSUE THREAD

**Issue by ttangGC** [HeliosOrg/SimpleDataIntegration#3]
The plugin is working great within the UE4 editor (Engine Version 4.12.5) and the preview modes, but when I try to use launch from device or package the project, the build fails to compile. I've tried starting a fresh Third Person Shooter project and compiled the game without the plugin just fine, but when I include the plugin, the project fails to package.

I'm looking to use a tablet with an optimized version of the VR application I've created, so someone can externally direct the VR user with a tablet. I've tried compiling on both windows and on android.

```
LogPlayLevel: UnrealBuildTool: Module.SimpleDataIntegration.cpp
LogPlayLevel: UnrealBuildTool: C:\Program Files (x86)\Epic Games\4.12\Engine\Source\Editor\GraphEditor\Public\GraphEditorSettings.h(6): fatal error C1083: Cannot open include file: 'GraphEditorSettings.generated.h': No such file or directory
LogPlayLevel: UnrealBuildTool: C:\Program Files (x86)\Epic Games\4.12\Engine\Source\Editor\GraphEditor\Public\GraphEditorSettings.h(6): fatal error C1083: Cannot open include file: 'GraphEditorSettings.generated.h': No such file or directory
LogPlayLevel: UnrealBuildTool: ERROR: UBT ERROR: Failed to produce item: V:\0908 The Stage VR\VR\TheStageVR_iPad\Plugins\SimpleDataIntegration\Binaries\Win64\UE4-SimpleDataIntegration.lib
LogPlayLevel: UnrealBuildTool: Total build time: 19.10 seconds
LogPlayLevel: CommandUtils.Run: Run: Took 19.2299643s to run UnrealBuildTool.exe, ExitCode=5
LogPlayLevel: Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.AutomationException: Command failed (Result:5): C:\Program Files (x86)\Epic Games\4.12\Engine\Binaries\DotNET\UnrealBuildTool.exe TheStageVR_iPad Win64 Development -Project="V:\0908 The Stage VR\VR\TheStageVR_iPad\TheStageVR_iPad.uproject"  "V:\0908 The Stage VR\VR\Th
eStageVR_iPad\TheStageVR_iPad.uproject"  -remoteini="V:\0908 The Stage VR\VR\TheStageVR_iPad" -noxge -NoHotReloadFromIDE -ignorejunk. See logfile for details: 'UnrealBuildTool-2016.08.19-17.45.56.txt'
LogPlayLevel:    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars)
LogPlayLevel:    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)
LogPlayLevel:    at AutomationTool.UE4Build.BuildWithUBT(String TargetName, UnrealTargetPlatform TargetPlatform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars)
LogPlayLevel:    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictionary`2 InTargetToManifest)
LogPlayLevel:    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask)
LogPlayLevel:    at BuildCookRun.DoBuildCookRun(ProjectParams Params)
LogPlayLevel:    at AutomationTool.BuildCommand.Execute()
LogPlayLevel:    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
LogPlayLevel:    at AutomationTool.Automation.Process(String[] CommandLine)
LogPlayLevel:    at AutomationTool.Program.MainProc(Object Param)
LogPlayLevel:    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param)
LogPlayLevel:    at AutomationTool.Program.Main()
LogPlayLevel: Program.Main: AutomationTool exiting with ExitCode=5 (5)
LogPlayLevel: Domain_ProcessExit
LogPlayLevel: copying UAT log files...
LogPlayLevel: Completed Launch On Stage: Build Task, Time: 20.025862
LogPlayLevel: BUILD FAILED
PackagingResults:Error: Error Launch failed! Unknown Error
```

I also get this warning numerous times in the output log:

`LogTemp:Warning: Helios > getter node title`

Are you able to compile projects with this plugin?

**Comment by colorofblack** [comment]
Any news on this? I'm trying to package a project with Version 4.13.1 and am getting the same / similar error messages:

[2016.10.24-08.38.43:741][619]UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: Module.SimpleDataIntegration.cpp

[2016.10.24-08.38.43:750][620]UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: SimpleDataIntegration.generated.cpp

[2016.10.24-08.39.00:098][559]UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: C:\Applications\Epic Games\4.13\Engine\Source\Editor\GraphEditor\Public\GraphEditorSettings.h(6): fatal error C1083: Cannot open include file: 'GraphEditorSettings.generated.h': No such file or directory

[2016.10.24-08.39.00:158][566]UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: C:\Applications\Epic Games\4.13\Engine\Source\Editor\GraphEditor\Public\GraphEditorSettings.h(6): fatal error C1083: Cannot open include file: 'GraphEditorSettings.generated.h': No such file or directory

[2016.10.24-08.39.01:350][705]UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: ERROR: UBT ERROR: Failed to produce item: C:\UE4_Projects\PushConfVR2016\Plugins\SimpleDataIntegration\Binaries\Win64\UE4-SimpleDataIntegration.lib

[2016.10.24-08.39.01:358][706]UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: Total build time: 19,59 seconds

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: Took 19,7215178s to run UnrealBuildTool.exe, ExitCode=5

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): C:\Applications\Epic Games\4.13\Engine\Binaries\DotNET\UnrealBuildTool.exe PushVR2016 Win64 Development -Project=C:\UE4_Projects\PushConfVR2016\PushVR2016.uproject  C:\UE4_Projects\PushConfVR2016\PushVR2016.uproject  -remoteini="C:\UE4_Projects\PushConfVR2016" -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2016.10.24-10.38.41.txt' 

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunAndLog(CommandEnvironment Env, String App, String CommandLine, String LogName, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, FileReference Project, String Target, String Platform, String Config, String AdditionalArgs, String LogName, Dictionary`2 EnvVars)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.BuildWithUBT(String TargetName, UnrealTargetPlatform TargetPlatform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictionary`2 InTargetToManifest)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at BuildCookRun.DoBuildCookRun(ProjectParams Params)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.BuildCommand.Execute()

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Process(String[] Arguments)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Program.MainProc(Object Param)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param)

[2016.10.24-08.39.01:469][719]UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Program.Main()

[2016.10.24-08.39.01:475][720]UATHelper: Packaging (Windows (64-bit)): Program.Main: AutomationTool exiting with ExitCode=5 (5)

[2016.10.24-08.39.01:493][722]UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
