### ISSUE TITLE
Build Fails (Non-editor build cannot depend on non-redistributable modules.)

### ISSUE THREAD

**Issue by colorofblack** [HeliosOrg/SimpleDataIntegration#6]
Hey everyone, 
we just finished a small prototype using your plugin. It works like a charm in the editor / VR Preview, but if we try to package the project we get the following error in the editor: 

`LogSavePackage: Moving '../../../../../../UE4_Projects/PushConfVR2016_packaging/Saved/UEDPCStrangerThingsViveMap1E021BCB4DC684C32CD7989270C0C744.tmp' to '../../../../../../UE4_Projects/PushConfVR2016_packaging/Saved/Autosaves/Game/StrangerThings/UEDPCStrangerThingsViveMap.umap'
LogSavePackage:Display: Finished SavePackage ../../../../../../UE4_Projects/PushConfVR2016_packaging/Saved/Autosaves/Game/StrangerThings/UEDPCStrangerThingsViveMap.umap
LogEditorTransaction: Undo Spawn Play From Here Start
UATHelper: Packaging (Windows (64-bit)): Running AutomationTool...
UATHelper: Packaging (Windows (64-bit)): Automation.ParseCommandLine: Parsing command line: -ScriptsForProject=C:/UE4_Projects/PushConfVR2016_packaging/PushVR2016.uproject BuildCookRun -nocompile -nocompileeditor -installed -nop4 -project=C:/UE4_Projects/PushConfVR2016_packaging/PushVR2016.uproject -cook -stage -archive -archivedirectory=C:/Users/17K-Daniel/
Desktop/PushVR2016 -package -clientconfig=Shipping -ue4exe=UE4Editor-Cmd.exe -clean -prereqs -distribution -nodebuginfo -targetplatform=Win64 -build -CrashReporter -utf8output
UATHelper: Packaging (Windows (64-bit)): Automation.Process: Setting up command environment.
UATHelper: Packaging (Windows (64-bit)): BuildCookRun.SetupParams: Setting up ProjectParams for C:\UE4_Projects\PushConfVR2016_packaging\PushVR2016.uproject
UATHelper: Packaging (Windows (64-bit)): Project.Build: ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: C:\Applications\Epic Games\4.13\Engine\Binaries\DotNET\UnrealBuildTool.exe PushVR2016 Win64 Shipping -Project=C:\UE4_Projects\PushConfVR2016_packaging\PushVR2016.uproject -clean C:\UE4_Projects\PushConfVR2016_packaging\PushVR2016.uproject  -remoteini="C:\UE4_Projects\PushConfVR2016_packaging" -n
obuilduht -NoHotReload
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: ERROR: Non-editor build cannot depend on non-redistributable modules. Details:
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: Binary C:\UE4_Projects\PushConfVR2016_packaging\Binaries\Win64\PushVR2016-Win64-Shipping.exe depends on: EditorStyle, SourceControl, WorkspaceMenuStructure, CurveAssetEditor, CrashTracker, DesktopPlatform, TargetPlatform, MessageLog, ClassViewer, Settings, HardwareTargeting, DirectoryWatcher, WidgetCa
rousel, SuperSearch, AddContentDialog, SourceCodeAccess, Documentation, GameProjectGeneration, UATHelper, Merge, BlueprintGraph, KismetWidgets, ExternalImagePicker, SharedSettingsWidgets, DerivedDataCache, HotReload, ActorPickerMode, StatsViewer, DeviceProfileServices, SceneOutliner, Persona, MovieSceneCaptureDialog, SequencerWidgets, SequenceRecorderSection
s, Sequencer, RawMesh, MaterialUtilities, MeshBoneReduction, MeshSimplifier, MeshUtilitie
UATHelper: Packaging (Windows (64-bit)): s, HierarchicalLODUtilities, HierarchicalLODOutliner, PixelInspectorModule, FbxAutomationBuilderModule, DeviceManager, SettingsEditor, UnrealEdMessages, AutomationController, AutomationWindow, ScreenShotComparisonTools, ScreenShotComparison, ProfilerMessages, ProfilerClient, Profiler, SessionFrontend, SlateReflector, 
Layers, LandscapeEditor, WorldBrowser, NewLevelDialog, DeviceProfileEditor, CollectionManager, PlacementMode, UserFeedback, TreeMap, SizeMap, ReferenceViewer, LauncherServices, IntroTutorials, ViewportInteraction, VREditor, LevelEditor, SequenceRecorder, MovieSceneTools, FunctionalTesting, KismetCompiler, BlueprintCompilerCppBackend, BlueprintNativeCodeGen, 
BlueprintProfiler, Kismet, GraphEditor, Localization, LocalizationService, TranslationEditor, UndoHistory, ProjectTargetPlatformEditor, OutputLog, EditorLiveStreaming, LocalizationDashboard, MainFrame, TextureEditor, CurveTableEditor, DataTableEditor, DestructibleMeshEditor, MaterialEditor, DesktopWidgets, FontEditor, SoundCueEditor, SoundClassEditor, AssetT
ools, SourceControlWindows, ContentBrowser, AnimGraph, InputBindingEditor, SwarmInterface, TargetDeviceServices, InternationalizationSettings, MeshPaint, PluginWarden, BspMode, GameplayDebugger, StaticMeshEditor, DistCurveEditor, Cascade, ConfigEditor, ComponentVisualizers, DetailCustomizations, UMGEditor, Matinee, EditorSettingsViewer, PackagesDialog, PhAT,
 ProjectLauncher, GeometryMode, TextureAlignMode, FoliageEdit, PackageDependencyInfo, Blutility, NiagaraEditor, MergeActors, ProjectSettingsViewer, PListEditor, AIGraph, BehaviorTreeEditor, EnvironmentQueryEditor, ViewportSnapping, GameplayTagsEditor, GameplayTasksEditor, GameplayAbilitiesEditor, IOSPlatformEditor, HTML5TargetPlatform, HTML5PlatformEditor, G
eometryCacheEd, AndroidDeviceDetection, AndroidPlatformEditor, UnrealEd, EditorWidgets, SceneDepthPickerMode, PropertyEditor.
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: Binary C:\UE4_Projects\PushConfVR2016_packaging\Plugins\SimpleDataIntegration\Binaries\Win64\UE4-SimpleDataIntegration-Win64-Shipping.lib depends on: EditorStyle, SourceControl, WorkspaceMenuStructure, CurveAssetEditor, CrashTracker, DesktopPlatform, TargetPlatform, MessageLog, ClassViewer, Settings, 
HardwareTargeting, DirectoryWatcher, WidgetCarousel, SuperSearch, AddContentDialog, SourceCodeAccess, Documentation, GameProjectGeneration, UATHelper, Merge, BlueprintGraph, KismetWidgets, ExternalImagePicker, SharedSettingsWidgets, DerivedDataCache, HotReload, ActorPickerMode, StatsViewer, DeviceProfileServices, SceneOutliner, Persona, MovieSceneCaptureDial
og, SequencerWidgets, SequenceRecorderSections, Sequencer, RawMesh, MaterialUtilities, MeshBoneReduction, MeshSimplifier, MeshUtilities, HierarchicalLODUtilities, HierarchicalLODOutliner, PixelInspectorModule, FbxAutomationBuilderModule, DeviceManager, SettingsEditor, UnrealEdMessages, AutomationController, AutomationWindow, ScreenShotComparisonTools, Screen
ShotComparison, ProfilerMessages, ProfilerClient, Profiler, SessionFrontend, SlateReflector, Layers, LandscapeEditor, WorldBrowser, NewLevelDialog, DeviceProfileEditor, CollectionManager, PlacementMode, UserFeedback, TreeMap, SizeMap, ReferenceViewer, LauncherServices, IntroTutorials, ViewportInteraction, VREditor, LevelEditor, SequenceRecorder, MovieSceneTo
ols, FunctionalTesting, KismetCompiler, BlueprintCompilerCppBackend, BlueprintNativeCodeGen, BlueprintProfiler, Kismet, GraphEditor, Localization, LocalizationService, TranslationEditor, UndoHistory, ProjectTargetPlatformEditor, OutputLog, EditorLiveStreaming, LocalizationDashboard, MainFrame, TextureEditor, CurveTableEditor, DataTableEditor, DestructibleMes
hEditor, MaterialEditor, DesktopWidgets, FontEditor, SoundCueEditor, SoundClassEditor, AssetTools, SourceControlWindows, ContentBrowser, AnimGraph, InputBindingEditor, SwarmInterface, TargetDeviceServices, InternationalizationSettings, MeshPaint, PluginWarden, BspMode, GameplayDebugger, StaticMeshEditor, DistCurveEditor, Cascade, ConfigEditor, ComponentVisua
lizers, DetailCustomizations, UMGEditor, Matinee, EditorSettingsViewer, PackagesDialog, PhAT, ProjectLauncher, GeometryMode, TextureAlignMode, FoliageEdit, PackageDependencyInfo, Blutility, NiagaraEditor, MergeActors, ProjectSettingsViewer, PListEditor, AIGraph, BehaviorTreeEditor, EnvironmentQueryEditor, ViewportSnapping, GameplayTagsEditor, GameplayTasksEd
itor, GameplayAbilitiesEditor, IOSPlatformEditor, HTML5TargetPlatform, HTML5PlatformEditor, GeometryCacheEd, AndroidDeviceDetection, AndroidPlatformEditor, UnrealEd, EditorWidgets, SceneDepthPickerMode, PropertyEditor.
UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: Took 0,7058775s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (Windows (64-bit)): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): C:\Applications\Epic Games\4.13\Engine\Binaries\DotNET\UnrealBuildTool.exe PushVR2016 Win64 Shipping -Project=C:\UE4_Projects\PushConfVR2016_packaging\PushVR2016.uproject -clean
 C:\UE4_Projects\PushConfVR2016_packaging\PushVR2016.uproject  -remoteini="C:\UE4_Projects\PushConfVR2016_packaging" -nobuilduht -NoHotReload. See logfile for details: 'UnrealBuildTool-2016.10.24-15.48.46.txt' 
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunAndLog(CommandEnvironment Env, String App, String CommandLine, String LogName, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, FileReference Project, String Target, String Platform, String Config, String AdditionalArgs, String LogName, Dictionary`2 EnvVars)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.CleanWithUBT(String TargetName, UnrealTargetPlatform Platform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Bo
UATHelper: Packaging (Windows (64-bit)): olean ForceDebugInfo, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictio
nary`2 InTargetToManifest)
UATHelper: Packaging (Windows (64-bit)):    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask)
UATHelper: Packaging (Windows (64-bit)):    at BuildCookRun.DoBuildCookRun(ProjectParams Params)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.BuildCommand.Execute()
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Process(String[] Arguments)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Program.MainProc(Object Param)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Program.Main()
UATHelper: Packaging (Windows (64-bit)): Program.Main: AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults:Error: Error Unknown Error`

And this error in VS2015: 
`Severity   Code    Description Project File    Line    Suppression State
Error       Non-editor build cannot depend on non-redistributable modules. Details: PushVR2016  C:\UE4_Projects\PushConfVR2016_packaging\Intermediate\ProjectFiles\EXEC 1   
Error   MSB3075 The command ""C:\Applications\Epic Games\4.13\Engine\Build\BatchFiles\Build.bat" PushVR2016 Win64 Shipping "C:\UE4_Projects\PushConfVR2016_packaging\PushVR2016.uproject" -waitmutex" exited with code 5. Please verify that you have sufficient rights to run this command.    PushVR2016  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets   41  
`
Any idea on how to fix it? (If I switch from shipping to development, I see an error indicating that it's the SDI plugin that is causing these errors) plus this one: 

`Trying to build in the UE with development settings under package results in: 
UATHelper: Packaging (Windows (32-bit)): UnrealBuildTool: C:\Applications\Epic Games\4.13\Engine\Source\Editor\GraphEditor\Public\GraphEditorSettings.h(6): fatal error C1083: Cannot open include file: 'GraphEditorSettings.generated.h': No such file or directory
I'm not sure if this is connected (probably)`

Help would be greatly appreciated

**Comment by zaha** [comment]
I get the same build error when trying to package a blank C++ project after only adding the SDI plugin.

I then searched for the missing 'GraphEditorSettings.generated.h' file, found it and copied it to the location it expected. Then the next generated.h file was missing:

> UATHelper: Packaging (Windows (64-bit)): Automation.Process: Setting up command environment.
> UATHelper: Packaging (Windows (64-bit)): BuildCookRun.SetupParams: Setting up ProjectParams for D:\Workspace\UnrealEngine\SDI\SDI.uproject
> UATHelper: Packaging (Windows (64-bit)): Project.Build: *********\* BUILD COMMAND STARTED **********
> UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: D:\dev\Epic Games\4.13\Engine\Binaries\DotNET\UnrealBuildTool.exe SDI Win64 Development -Project=D:\Workspace\UnrealEngine\SDI\SDI.uproject  D:\Workspace\UnrealEngine\SDI\SDI.uproject  -remoteini="D:\Workspace\UnrealEngine\SDI" -noxge -generatemanifest -NoHotReload
> UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: Performing full C++ include scan (building a new target)
> UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: Took 0,9494099s to run UnrealBuildTool.exe, ExitCode=0
> UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: D:\dev\Epic Games\4.13\Engine\Binaries\DotNET\UnrealBuildTool.exe SDI Win64 Development -Project=D:\Workspace\UnrealEngine\SDI\SDI.uproject  D:\Workspace\UnrealEngine\SDI\SDI.uproject  -remoteini="D:\Workspace\UnrealEngine\SDI" -noxge -NoHotReload -ignorejunk
> UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: Performing 4 actions (4 in parallel)
> UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: Module.SimpleDataIntegration.cpp
> UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: SimpleDataIntegration.generated.cpp
> UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: D:\dev\Epic Games\4.13\Engine\Source\Editor\BlueprintGraph\Classes\EdGraphSchema_K2.h(6): fatal error C1083: Cannot open include file: 'EdGraphSchema_K2.generated.h': No such file or directory
> UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: D:\dev\Epic Games\4.13\Engine\Source\Editor\BlueprintGraph\Classes\EdGraphSchema_K2.h(6): fatal error C1083: Cannot open include file: 'EdGraphSchema_K2.generated.h': No such file or directory
> UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: ERROR: UBT ERROR: Failed to produce item: D:\Workspace\UnrealEngine\SDI\Plugins\SimpleDataIntegration\Binaries\Win64\UE4-SimpleDataIntegration.lib
> UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: Total build time: 26,54 seconds
> UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: Took 26,7001075s to run UnrealBuildTool.exe, ExitCode=5
> UATHelper: Packaging (Windows (64-bit)): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): D:\dev\Epic Games\4.13\Engine\Binaries\DotNET\UnrealBuildTool.exe SDI Win64 Development -Project=D:\Workspace\Unre
> UATHelper: Packaging (Windows (64-bit)): alEngine\SDI\SDI.uproject  D:\Workspace\UnrealEngine\SDI\SDI.uproject  -remoteini="D:\Workspace\UnrealEngine\SDI" -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2016.10.25-18.46.54.txt' 
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunAndLog(CommandEnvironment Env, String App, String CommandLine, String LogName, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, FileReference Project, String Target, String Platform, String Config, String AdditionalArgs, String LogName, Dictionary`2 EnvVars)
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.BuildWithUBT(String TargetName, UnrealTargetPlatform TargetPlatform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars)
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictio
> nary`2 InTargetToManifest)
> UATHelper: Packaging (Windows (64-bit)):    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask)
> UATHelper: Packaging (Windows (64-bit)):    at BuildCookRun.DoBuildCookRun(ProjectParams Params)
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.BuildCommand.Execute()
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Process(String[] Arguments)
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Program.MainProc(Object Param)
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param)
> UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Program.Main()
> UATHelper: Packaging (Windows (64-bit)): Program.Main: AutomationTool exiting with ExitCode=5 (5)
> UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
> PackagingResults:Error: Error Unknown Error

It appears that there is something going wrong in the build process with where it is looking for these generated files. It expects them under 'Engine\Source\', when they are actually under '\Engine\Intermediate\Build\Win64\UE4Editor\Inc\'.

**Comment by ttangGC** [comment]
Hey,
I've since moved on from this plugin and found this alternative that works and compiles for me:
https://forums.unrealengine.com/showthread.php?7045-JSON-Query
This plugin is a whole lot more simpler in C++ code and is compatible with the Helios SDI server setup.
The older versions of the plugin won't work on Unreal 4.12+, but somewhere later in the plugin thread, someone compiled a 4.11 version that should build fine with 4.12 and 4.13.

**Comment by colorofblack** [comment]
Hey ttangGC, 
thanks for your reply, I did the same, though the JSON-Query plugin crashed sometimes for me so I switched to https://www.unrealengine.com/marketplace/low-entry-socket-connection and the json plugin from LE...needed some rebuilding and tweaking but works great and you can package it without any problems. 

Still an answer from the developers would be great, as this plugin was featured by epic and I'm sure we're not the only ones having those problems :-)
